#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT_Construction
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mt_construction")]
	public partial class EntidadesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcategoria(categoria instance);
    partial void Updatecategoria(categoria instance);
    partial void Deletecategoria(categoria instance);
    partial void Insertcarrito(carrito instance);
    partial void Updatecarrito(carrito instance);
    partial void Deletecarrito(carrito instance);
    partial void Insertcategoria_producto(categoria_producto instance);
    partial void Updatecategoria_producto(categoria_producto instance);
    partial void Deletecategoria_producto(categoria_producto instance);
    partial void Insertestado(estado instance);
    partial void Updateestado(estado instance);
    partial void Deleteestado(estado instance);
    partial void Insertmetodo_pago(metodo_pago instance);
    partial void Updatemetodo_pago(metodo_pago instance);
    partial void Deletemetodo_pago(metodo_pago instance);
    partial void Insertorden(orden instance);
    partial void Updateorden(orden instance);
    partial void Deleteorden(orden instance);
    partial void Insertorden_detalle(orden_detalle instance);
    partial void Updateorden_detalle(orden_detalle instance);
    partial void Deleteorden_detalle(orden_detalle instance);
    partial void Insertproducto(producto instance);
    partial void Updateproducto(producto instance);
    partial void Deleteproducto(producto instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    partial void Insertventa(venta instance);
    partial void Updateventa(venta instance);
    partial void Deleteventa(venta instance);
    #endregion
		
		public EntidadesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mt_constructionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categoria> categoria
		{
			get
			{
				return this.GetTable<categoria>();
			}
		}
		
		public System.Data.Linq.Table<carrito> carrito
		{
			get
			{
				return this.GetTable<carrito>();
			}
		}
		
		public System.Data.Linq.Table<categoria_producto> categoria_producto
		{
			get
			{
				return this.GetTable<categoria_producto>();
			}
		}
		
		public System.Data.Linq.Table<estado> estado
		{
			get
			{
				return this.GetTable<estado>();
			}
		}
		
		public System.Data.Linq.Table<metodo_pago> metodo_pago
		{
			get
			{
				return this.GetTable<metodo_pago>();
			}
		}
		
		public System.Data.Linq.Table<orden> orden
		{
			get
			{
				return this.GetTable<orden>();
			}
		}
		
		public System.Data.Linq.Table<orden_detalle> orden_detalle
		{
			get
			{
				return this.GetTable<orden_detalle>();
			}
		}
		
		public System.Data.Linq.Table<producto> producto
		{
			get
			{
				return this.GetTable<producto>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuario
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		public System.Data.Linq.Table<venta> venta
		{
			get
			{
				return this.GetTable<venta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categoria")]
	public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_cate;
		
		private string _nombre;
		
		private EntitySet<categoria_producto> _categoria_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_cateChanging(int value);
    partial void Oncod_cateChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public categoria()
		{
			this._categoria_producto = new EntitySet<categoria_producto>(new Action<categoria_producto>(this.attach_categoria_producto), new Action<categoria_producto>(this.detach_categoria_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cate", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cod_cate
		{
			get
			{
				return this._cod_cate;
			}
			set
			{
				if ((this._cod_cate != value))
				{
					this.Oncod_cateChanging(value);
					this.SendPropertyChanging();
					this._cod_cate = value;
					this.SendPropertyChanged("cod_cate");
					this.Oncod_cateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_categoria_producto", Storage="_categoria_producto", ThisKey="cod_cate", OtherKey="cod_cate")]
		public EntitySet<categoria_producto> categoria_producto
		{
			get
			{
				return this._categoria_producto;
			}
			set
			{
				this._categoria_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_categoria_producto(categoria_producto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = this;
		}
		
		private void detach_categoria_producto(categoria_producto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.carrito")]
	public partial class carrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_carrito;
		
		private int _cantidad;
		
		private int _id_usuario;
		
		private int _id_producto;
		
		private EntityRef<producto> _producto;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_carritoChanging(int value);
    partial void Onid_carritoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    #endregion
		
		public carrito()
		{
			this._producto = default(EntityRef<producto>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_carrito", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_carrito
		{
			get
			{
				return this._id_carrito;
			}
			set
			{
				if ((this._id_carrito != value))
				{
					this.Onid_carritoChanging(value);
					this.SendPropertyChanging();
					this._id_carrito = value;
					this.SendPropertyChanged("id_carrito");
					this.Onid_carritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_carrito", Storage="_producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.carrito.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.carrito.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_carrito", Storage="_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.carrito.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.carrito.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categoria_producto")]
	public partial class categoria_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private int _cod_cate;
		
		private int _id_producto;
		
		private EntityRef<categoria> _categoria;
		
		private EntityRef<producto> _producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Oncod_cateChanging(int value);
    partial void Oncod_cateChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    #endregion
		
		public categoria_producto()
		{
			this._categoria = default(EntityRef<categoria>);
			this._producto = default(EntityRef<producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cate", DbType="Int NOT NULL")]
		public int cod_cate
		{
			get
			{
				return this._cod_cate;
			}
			set
			{
				if ((this._cod_cate != value))
				{
					if (this._categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_cateChanging(value);
					this.SendPropertyChanging();
					this._cod_cate = value;
					this.SendPropertyChanged("cod_cate");
					this.Oncod_cateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_categoria_producto", Storage="_categoria", ThisKey="cod_cate", OtherKey="cod_cate", IsForeignKey=true)]
		public categoria categoria
		{
			get
			{
				return this._categoria.Entity;
			}
			set
			{
				categoria previousValue = this._categoria.Entity;
				if (((previousValue != value) 
							|| (this._categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categoria.Entity = null;
						previousValue.categoria_producto.Remove(this);
					}
					this._categoria.Entity = value;
					if ((value != null))
					{
						value.categoria_producto.Add(this);
						this._cod_cate = value.cod_cate;
					}
					else
					{
						this._cod_cate = default(int);
					}
					this.SendPropertyChanged("categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_categoria_producto", Storage="_producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.categoria_producto.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.categoria_producto.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.estado")]
	public partial class estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_estado;
		
		private string _descripcion;
		
		private EntitySet<producto> _producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_estadoChanging(int value);
    partial void Oncod_estadoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public estado()
		{
			this._producto = new EntitySet<producto>(new Action<producto>(this.attach_producto), new Action<producto>(this.detach_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_estado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cod_estado
		{
			get
			{
				return this._cod_estado;
			}
			set
			{
				if ((this._cod_estado != value))
				{
					this.Oncod_estadoChanging(value);
					this.SendPropertyChanging();
					this._cod_estado = value;
					this.SendPropertyChanged("cod_estado");
					this.Oncod_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estado_producto", Storage="_producto", ThisKey="cod_estado", OtherKey="cod_estado")]
		public EntitySet<producto> producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				this._producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.estado = this;
		}
		
		private void detach_producto(producto entity)
		{
			this.SendPropertyChanging();
			entity.estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.metodo_pago")]
	public partial class metodo_pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cod_metodo;
		
		private string _descripcion;
		
		private EntitySet<orden> _orden;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncod_metodoChanging(int value);
    partial void Oncod_metodoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public metodo_pago()
		{
			this._orden = new EntitySet<orden>(new Action<orden>(this.attach_orden), new Action<orden>(this.detach_orden));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_metodo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cod_metodo
		{
			get
			{
				return this._cod_metodo;
			}
			set
			{
				if ((this._cod_metodo != value))
				{
					this.Oncod_metodoChanging(value);
					this.SendPropertyChanging();
					this._cod_metodo = value;
					this.SendPropertyChanged("cod_metodo");
					this.Oncod_metodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="metodo_pago_orden", Storage="_orden", ThisKey="cod_metodo", OtherKey="cod_metodo")]
		public EntitySet<orden> orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				this._orden.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orden(orden entity)
		{
			this.SendPropertyChanging();
			entity.metodo_pago = this;
		}
		
		private void detach_orden(orden entity)
		{
			this.SendPropertyChanging();
			entity.metodo_pago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orden")]
	public partial class orden : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _folio_orden;
		
		private int _cantidad;
		
		private int _precio_total;
		
		private int _id_usuario;
		
		private int _cod_metodo;
		
		private int _id_producto;
		
		private EntitySet<orden_detalle> _orden_detalle;
		
		private EntitySet<venta> _venta;
		
		private EntityRef<metodo_pago> _metodo_pago;
		
		private EntityRef<producto> _producto;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfolio_ordenChanging(int value);
    partial void Onfolio_ordenChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void Onprecio_totalChanging(int value);
    partial void Onprecio_totalChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Oncod_metodoChanging(int value);
    partial void Oncod_metodoChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    #endregion
		
		public orden()
		{
			this._orden_detalle = new EntitySet<orden_detalle>(new Action<orden_detalle>(this.attach_orden_detalle), new Action<orden_detalle>(this.detach_orden_detalle));
			this._venta = new EntitySet<venta>(new Action<venta>(this.attach_venta), new Action<venta>(this.detach_venta));
			this._metodo_pago = default(EntityRef<metodo_pago>);
			this._producto = default(EntityRef<producto>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio_orden", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int folio_orden
		{
			get
			{
				return this._folio_orden;
			}
			set
			{
				if ((this._folio_orden != value))
				{
					this.Onfolio_ordenChanging(value);
					this.SendPropertyChanging();
					this._folio_orden = value;
					this.SendPropertyChanged("folio_orden");
					this.Onfolio_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_total", DbType="Int NOT NULL")]
		public int precio_total
		{
			get
			{
				return this._precio_total;
			}
			set
			{
				if ((this._precio_total != value))
				{
					this.Onprecio_totalChanging(value);
					this.SendPropertyChanging();
					this._precio_total = value;
					this.SendPropertyChanged("precio_total");
					this.Onprecio_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_metodo", DbType="Int NOT NULL")]
		public int cod_metodo
		{
			get
			{
				return this._cod_metodo;
			}
			set
			{
				if ((this._cod_metodo != value))
				{
					if (this._metodo_pago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_metodoChanging(value);
					this.SendPropertyChanging();
					this._cod_metodo = value;
					this.SendPropertyChanged("cod_metodo");
					this.Oncod_metodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orden_orden_detalle", Storage="_orden_detalle", ThisKey="folio_orden", OtherKey="folio_orden")]
		public EntitySet<orden_detalle> orden_detalle
		{
			get
			{
				return this._orden_detalle;
			}
			set
			{
				this._orden_detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orden_venta", Storage="_venta", ThisKey="folio_orden", OtherKey="folio_orden")]
		public EntitySet<venta> venta
		{
			get
			{
				return this._venta;
			}
			set
			{
				this._venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="metodo_pago_orden", Storage="_metodo_pago", ThisKey="cod_metodo", OtherKey="cod_metodo", IsForeignKey=true)]
		public metodo_pago metodo_pago
		{
			get
			{
				return this._metodo_pago.Entity;
			}
			set
			{
				metodo_pago previousValue = this._metodo_pago.Entity;
				if (((previousValue != value) 
							|| (this._metodo_pago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._metodo_pago.Entity = null;
						previousValue.orden.Remove(this);
					}
					this._metodo_pago.Entity = value;
					if ((value != null))
					{
						value.orden.Add(this);
						this._cod_metodo = value.cod_metodo;
					}
					else
					{
						this._cod_metodo = default(int);
					}
					this.SendPropertyChanged("metodo_pago");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_orden", Storage="_producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.orden.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.orden.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_orden", Storage="_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.orden.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.orden.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orden_detalle(orden_detalle entity)
		{
			this.SendPropertyChanging();
			entity.orden = this;
		}
		
		private void detach_orden_detalle(orden_detalle entity)
		{
			this.SendPropertyChanging();
			entity.orden = null;
		}
		
		private void attach_venta(venta entity)
		{
			this.SendPropertyChanging();
			entity.orden = this;
		}
		
		private void detach_venta(venta entity)
		{
			this.SendPropertyChanging();
			entity.orden = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orden_detalle")]
	public partial class orden_detalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ordendetalle;
		
		private int _folio_orden;
		
		private int _id_venta;
		
		private EntityRef<orden> _orden;
		
		private EntityRef<venta> _venta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ordendetalleChanging(int value);
    partial void Onid_ordendetalleChanged();
    partial void Onfolio_ordenChanging(int value);
    partial void Onfolio_ordenChanged();
    partial void Onid_ventaChanging(int value);
    partial void Onid_ventaChanged();
    #endregion
		
		public orden_detalle()
		{
			this._orden = default(EntityRef<orden>);
			this._venta = default(EntityRef<venta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ordendetalle", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_ordendetalle
		{
			get
			{
				return this._id_ordendetalle;
			}
			set
			{
				if ((this._id_ordendetalle != value))
				{
					this.Onid_ordendetalleChanging(value);
					this.SendPropertyChanging();
					this._id_ordendetalle = value;
					this.SendPropertyChanged("id_ordendetalle");
					this.Onid_ordendetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio_orden", DbType="Int NOT NULL")]
		public int folio_orden
		{
			get
			{
				return this._folio_orden;
			}
			set
			{
				if ((this._folio_orden != value))
				{
					if (this._orden.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfolio_ordenChanging(value);
					this.SendPropertyChanging();
					this._folio_orden = value;
					this.SendPropertyChanged("folio_orden");
					this.Onfolio_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", DbType="Int NOT NULL")]
		public int id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					if (this._venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ventaChanging(value);
					this.SendPropertyChanging();
					this._id_venta = value;
					this.SendPropertyChanged("id_venta");
					this.Onid_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orden_orden_detalle", Storage="_orden", ThisKey="folio_orden", OtherKey="folio_orden", IsForeignKey=true)]
		public orden orden
		{
			get
			{
				return this._orden.Entity;
			}
			set
			{
				orden previousValue = this._orden.Entity;
				if (((previousValue != value) 
							|| (this._orden.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._orden.Entity = null;
						previousValue.orden_detalle.Remove(this);
					}
					this._orden.Entity = value;
					if ((value != null))
					{
						value.orden_detalle.Add(this);
						this._folio_orden = value.folio_orden;
					}
					else
					{
						this._folio_orden = default(int);
					}
					this.SendPropertyChanged("orden");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venta_orden_detalle", Storage="_venta", ThisKey="id_venta", OtherKey="id_venta", IsForeignKey=true)]
		public venta venta
		{
			get
			{
				return this._venta.Entity;
			}
			set
			{
				venta previousValue = this._venta.Entity;
				if (((previousValue != value) 
							|| (this._venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._venta.Entity = null;
						previousValue.orden_detalle.Remove(this);
					}
					this._venta.Entity = value;
					if ((value != null))
					{
						value.orden_detalle.Add(this);
						this._id_venta = value.id_venta;
					}
					else
					{
						this._id_venta = default(int);
					}
					this.SendPropertyChanged("venta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producto")]
	public partial class producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_producto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private int _precio;
		
		private string _imagen;
		
		private int _cod_estado;
		
		private EntitySet<carrito> _carrito;
		
		private EntitySet<categoria_producto> _categoria_producto;
		
		private EntitySet<orden> _orden;
		
		private EntitySet<venta> _venta;
		
		private EntityRef<estado> _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprecioChanging(int value);
    partial void OnprecioChanged();
    partial void OnimagenChanging(string value);
    partial void OnimagenChanged();
    partial void Oncod_estadoChanging(int value);
    partial void Oncod_estadoChanged();
    #endregion
		
		public producto()
		{
			this._carrito = new EntitySet<carrito>(new Action<carrito>(this.attach_carrito), new Action<carrito>(this.detach_carrito));
			this._categoria_producto = new EntitySet<categoria_producto>(new Action<categoria_producto>(this.attach_categoria_producto), new Action<categoria_producto>(this.detach_categoria_producto));
			this._orden = new EntitySet<orden>(new Action<orden>(this.attach_orden), new Action<orden>(this.detach_orden));
			this._venta = new EntitySet<venta>(new Action<venta>(this.attach_venta), new Action<venta>(this.detach_venta));
			this._estado = default(EntityRef<estado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Int NOT NULL")]
		public int precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_estado", DbType="Int NOT NULL")]
		public int cod_estado
		{
			get
			{
				return this._cod_estado;
			}
			set
			{
				if ((this._cod_estado != value))
				{
					if (this._estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncod_estadoChanging(value);
					this.SendPropertyChanging();
					this._cod_estado = value;
					this.SendPropertyChanged("cod_estado");
					this.Oncod_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_carrito", Storage="_carrito", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<carrito> carrito
		{
			get
			{
				return this._carrito;
			}
			set
			{
				this._carrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_categoria_producto", Storage="_categoria_producto", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<categoria_producto> categoria_producto
		{
			get
			{
				return this._categoria_producto;
			}
			set
			{
				this._categoria_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_orden", Storage="_orden", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<orden> orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				this._orden.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_venta", Storage="_venta", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<venta> venta
		{
			get
			{
				return this._venta;
			}
			set
			{
				this._venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="estado_producto", Storage="_estado", ThisKey="cod_estado", OtherKey="cod_estado", IsForeignKey=true)]
		public estado estado
		{
			get
			{
				return this._estado.Entity;
			}
			set
			{
				estado previousValue = this._estado.Entity;
				if (((previousValue != value) 
							|| (this._estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._estado.Entity = null;
						previousValue.producto.Remove(this);
					}
					this._estado.Entity = value;
					if ((value != null))
					{
						value.producto.Add(this);
						this._cod_estado = value.cod_estado;
					}
					else
					{
						this._cod_estado = default(int);
					}
					this.SendPropertyChanged("estado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
		
		private void attach_categoria_producto(categoria_producto entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_categoria_producto(categoria_producto entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
		
		private void attach_orden(orden entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_orden(orden entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
		
		private void attach_venta(venta entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_venta(venta entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuario")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _correo;
		
		private string _contraseña;
		
		private string _rut;
		
		private string _nombre;
		
		private string _apellidos;
		
		private int _telefono;
		
		private string _calle;
		
		private int _numero;
		
		private string _comuna;
		
		private EntitySet<carrito> _carrito;
		
		private EntitySet<orden> _orden;
		
		private EntitySet<venta> _venta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OnrutChanging(string value);
    partial void OnrutChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OntelefonoChanging(int value);
    partial void OntelefonoChanged();
    partial void OncalleChanging(string value);
    partial void OncalleChanged();
    partial void OnnumeroChanging(int value);
    partial void OnnumeroChanged();
    partial void OncomunaChanging(string value);
    partial void OncomunaChanged();
    #endregion
		
		public usuario()
		{
			this._carrito = new EntitySet<carrito>(new Action<carrito>(this.attach_carrito), new Action<carrito>(this.detach_carrito));
			this._orden = new EntitySet<orden>(new Action<orden>(this.attach_orden), new Action<orden>(this.detach_orden));
			this._venta = new EntitySet<venta>(new Action<venta>(this.attach_venta), new Action<venta>(this.detach_venta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated = true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{

					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rut", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string rut
		{
			get
			{
				return this._rut;
			}
			set
			{
				if ((this._rut != value))
				{
					this.OnrutChanging(value);
					this.SendPropertyChanging();
					this._rut = value;
					this.SendPropertyChanged("rut");
					this.OnrutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int NOT NULL")]
		public int telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calle", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string calle
		{
			get
			{
				return this._calle;
			}
			set
			{
				if ((this._calle != value))
				{
					this.OncalleChanging(value);
					this.SendPropertyChanging();
					this._calle = value;
					this.SendPropertyChanged("calle");
					this.OncalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="Int NOT NULL")]
		public int numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comuna", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string comuna
		{
			get
			{
				return this._comuna;
			}
			set
			{
				if ((this._comuna != value))
				{
					this.OncomunaChanging(value);
					this.SendPropertyChanging();
					this._comuna = value;
					this.SendPropertyChanged("comuna");
					this.OncomunaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_carrito", Storage="_carrito", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<carrito> carrito
		{
			get
			{
				return this._carrito;
			}
			set
			{
				this._carrito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_orden", Storage="_orden", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<orden> orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				this._orden.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_venta", Storage="_venta", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<venta> venta
		{
			get
			{
				return this._venta;
			}
			set
			{
				this._venta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_carrito(carrito entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_orden(orden entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_orden(orden entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
		
		private void attach_venta(venta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = this;
		}
		
		private void detach_venta(venta entity)
		{
			this.SendPropertyChanging();
			entity.usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.venta")]
	public partial class venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venta;
		
		private int _folio_orden;
		
		private int _id_usuario;
		
		private int _id_producto;
		
		private EntitySet<orden_detalle> _orden_detalle;
		
		private EntityRef<orden> _orden;
		
		private EntityRef<producto> _producto;
		
		private EntityRef<usuario> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ventaChanging(int value);
    partial void Onid_ventaChanged();
    partial void Onfolio_ordenChanging(int value);
    partial void Onfolio_ordenChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    #endregion
		
		public venta()
		{
			this._orden_detalle = new EntitySet<orden_detalle>(new Action<orden_detalle>(this.attach_orden_detalle), new Action<orden_detalle>(this.detach_orden_detalle));
			this._orden = default(EntityRef<orden>);
			this._producto = default(EntityRef<producto>);
			this._usuario = default(EntityRef<usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					this.Onid_ventaChanging(value);
					this.SendPropertyChanging();
					this._id_venta = value;
					this.SendPropertyChanged("id_venta");
					this.Onid_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio_orden", DbType="Int NOT NULL")]
		public int folio_orden
		{
			get
			{
				return this._folio_orden;
			}
			set
			{
				if ((this._folio_orden != value))
				{
					if (this._orden.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfolio_ordenChanging(value);
					this.SendPropertyChanging();
					this._folio_orden = value;
					this.SendPropertyChanged("folio_orden");
					this.Onfolio_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="venta_orden_detalle", Storage="_orden_detalle", ThisKey="id_venta", OtherKey="id_venta")]
		public EntitySet<orden_detalle> orden_detalle
		{
			get
			{
				return this._orden_detalle;
			}
			set
			{
				this._orden_detalle.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orden_venta", Storage="_orden", ThisKey="folio_orden", OtherKey="folio_orden", IsForeignKey=true)]
		public orden orden
		{
			get
			{
				return this._orden.Entity;
			}
			set
			{
				orden previousValue = this._orden.Entity;
				if (((previousValue != value) 
							|| (this._orden.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._orden.Entity = null;
						previousValue.venta.Remove(this);
					}
					this._orden.Entity = value;
					if ((value != null))
					{
						value.venta.Add(this);
						this._folio_orden = value.folio_orden;
					}
					else
					{
						this._folio_orden = default(int);
					}
					this.SendPropertyChanged("orden");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_venta", Storage="_producto", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.venta.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.venta.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="usuario_venta", Storage="_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public usuario usuario
		{
			get
			{
				return this._usuario.Entity;
			}
			set
			{
				usuario previousValue = this._usuario.Entity;
				if (((previousValue != value) 
							|| (this._usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._usuario.Entity = null;
						previousValue.venta.Remove(this);
					}
					this._usuario.Entity = value;
					if ((value != null))
					{
						value.venta.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_orden_detalle(orden_detalle entity)
		{
			this.SendPropertyChanging();
			entity.venta = this;
		}
		
		private void detach_orden_detalle(orden_detalle entity)
		{
			this.SendPropertyChanging();
			entity.venta = null;
		}
	}
}
#pragma warning restore 1591
